version: '2.1'

services:

    app1:
        build: .
        environment:
         - INSTANCE_ID=2
        ports:
         - 8081:8080


    app2:
        build: .
        environment:
         - INSTANCE_ID=2
        ports:
         - 8082:8080

    app3:
        build: .
        environment:
         - INSTANCE_ID=3
        ports:
         - 8083:8080

    elk:
        image: sebp/elk:563
        volumes:
         - ./03-json-input.conf:/etc/logstash/conf.d/03-json-input.conf
         - ./30-output.conf:/etc/logstash/conf.d/30-output.conf
        ports:
         - 4560:4560
         - 5601:5601
         - 9200:9200
         - 5044:5044
