version: '2.1'

services:

    app1:
        build: .
        environment:
         - INSTANCE_ID=2
        ports:
         - 8081:8080


    app2:
        build: .
        environment:
         - INSTANCE_ID=2
        ports:
         - 8082:8080

    app3:
        build: .
        environment:
         - INSTANCE_ID=3
        ports:
         - 8083:8080

    elk:
        image: sebp/elk:563
        ports:
         - 5601:5601
         - 9200:9200
